[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.11", features = ["postgres", "chrono"] }
dotenvy = "0.15.7"
uuid = {version = "1.17.0", features = ["v4"]}
